name: Build the test project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-desktop:
    name: Build the test project
    strategy:
      matrix:
        include:
          - target: Windows
            os: windows-latest
          - target: macOS
            os: macos-latest
          - target: Linux
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Check out the main branch
        uses: actions/checkout@v4

      - name: Build the test project on ${{ matrix.target }}
        run: ./gradlew build
        working-directory: jawt-tests
